version: '3.8'

services:
  api:
    build: .
    # ports:
    #   - "5001:5000"
    env_file:
      - .env
    depends_on: # <--- MODIFY THIS SECTION
      - db
    environment:
      - DATABASE_URL=postgresql+psycopg2://shawn:password123@db:5432/task_manager_db


  db: # This is our new PostgreSQL database service
    image: postgres:15-alpine # Use an official, lightweight PostgreSQL image
    volumes:
      - postgres_data:/var/lib/postgresql/data/ # Persist database data
    environment:
      - POSTGRES_USER=shawn         # Replace with your desired username
      - POSTGRES_PASSWORD=password123 # Replace with your desired password
      - POSTGRES_DB=task_manager_db      # The name of the database to create
    ports:
      - "5432:5432" # Optional: Expose Postgres port to host for direct access

  nginx: # <--- ADD THIS NEW NGINX SERVICE
    image: nginx:alpine # Use the official lightweight Nginx image
    ports:
      - "80:80" # Map port 80 on your host to port 80 in the Nginx container
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf # Mount your nginx.conf into the container
    depends_on:
      - api # Nginx needs the API to be running to forward requests to it

# Add this section at the very end of the file to declare the volume
volumes:
  postgres_data: